In [65]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.simplefilter(action='ignore')

pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv('survey_results_public_2022.csv')
df = data.copy()
df.head()

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73268 entries, 0 to 73267
Data columns (total 79 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ResponseId                      73268 non-null  int64
 1   MainBranch                      73268 non-null  object
 2   Employment                      71709 non-null  object
 3   RemoteWork                      58958 non-null  object
 4   CodingActivities                58899 non-null  object
 5   EdLevel                         71571 non-null  object
 6   LearnCode                       71580 non-null  object
 7   LearnCodeOnline                 50685 non-null  object
 8   LearnCodeCoursesCert            29389 non-null  object
 9   YearsCode                       71331 non-null  object
 10  YearsCodePro                    51833 non-null  object
 11  DevType                         61302 non-null  object
 12  OrgSize                         51039 non-null  object
 13  PurchaseInfluence               50969 non-null  object
 14  BuyNewTool                      67963 non-null  object
 15  Country                         71771 non-null  object
 16  Currency                        51264 non-null  object
 17  CompTotal                       38422 non-null  float64
 18  CompFreq                        44425 non-null  object
 19  LanguageHaveWorkedWith          70975 non-null  object
 20  LanguageWantToWorkWith          67027 non-null  object
 21  DatabaseHaveWorkedWith          60121 non-null  object
 22  DatabaseWantToWorkWith          51014 non-null  object
 23  PlatformHaveWorkedWith          49924 non-null  object
 24  PlatformWantToWorkWith          40415 non-null  object
 25  WebframeHaveWorkedWith          53544 non-null  object
 26  WebframeWantToWorkWith          46122 non-null  object
 27  MiscTechHaveWorkedWith          44992 non-null  object
 28  MiscTechWantToWorkWith          36810 non-null  object
 29  ToolsTechHaveWorkedWith         54171 non-null  object
 30  ToolsTechWantToWorkWith         46566 non-null  object
 31  NEWCollabToolsHaveWorkedWith    70347 non-null  object
 32  NEWCollabToolsWantToWorkWith    64108 non-null  object
 33  OpSysProfessional use           65503 non-null  object
 34  OpSysPersonal use               70963 non-null  object
 35  VersionControlSystem            71379 non-null  object
 36  VCInteraction                   68156 non-null  object
 37  VCHostingPersonal use           0 non-null      float64
 38  VCHostingProfessional use       0 non-null      float64
 39  OfficeStackAsyncHaveWorkedWith  46223 non-null  object
 40  OfficeStackAsyncWantToWorkWith  32072 non-null  object
 41  OfficeStackSyncHaveWorkedWith   62128 non-null  object
 42  OfficeStackSyncWantToWorkWith   47688 non-null  object
 43  Blockchain                      71071 non-null  object
 44  NEWSOSites                      71365 non-null  object
 45  SOVisitFreq                     70961 non-null  object
 46  SOAccount                       71572 non-null  object
 47  SOPartFreq                      58229 non-null  object
 48  SOComm                          71408 non-null  object
 49  Age                             70946 non-null  object
 50  Gender                          70853 non-null  object
 51  Trans                           70315 non-null  object
 52  Sexuality                       66565 non-null  object
 53  Ethnicity                       69474 non-null  object
 54  Accessibility                   67244 non-null  object
 55  MentalHealth                    66447 non-null  object
 56  TBranch                         52670 non-null  object
 57  ICorPM                          36283 non-null  object
 58  WorkExp                         36769 non-null  float64
 59  Knowledge_1                     35804 non-null  object
 60  Knowledge_2                     34973 non-null  object
 61  Knowledge_3                     35133 non-null  object
 62  Knowledge_4                     35097 non-null  object
 63  Knowledge_5                     35014 non-null  object
 64  Knowledge_6                     34991 non-null  object
 65  Knowledge_7                     34977 non-null  object
 66  Frequency_1                     35371 non-null  object
 67  Frequency_2                     35344 non-null  object
 68  Frequency_3                     34515 non-null  object
 69  TimeSearching                   36198 non-null  object
 70  TimeAnswering                   36022 non-null  object
 71  Onboarding                      35679 non-null  object
 72  ProfessionalTech                34906 non-null  object
 73  TrueFalse_1                     35819 non-null  object
 74  TrueFalse_2                     35715 non-null  object
 75  TrueFalse_3                     35749 non-null  object
 76  SurveyLength                    70444 non-null  object
 77  SurveyEase                      70508 non-null  object
 78  ConvertedCompYearly             38071 non-null  float64
dtypes: float64(5), int64(1), object(73)
memory usage: 44.2+ MB

In [44]:
pd.options.display.float_format = '{:,.2f}'.format
df.describe()

,ResponseId,CompTotal,VCHostingPersonal use,VCHostingProfessional use,WorkExp,ConvertedCompYearly
count,"73,268.00","38,422.00",0.00,0.00,"36,769.00","38,071.00"
mean,"36,634.50","23,424,340,221,747,959,297,504,942,608,856,691,548,764,873,498,296,320.00",NaN,NaN,10.24,"170,761.28"
std,"21,150.79","4,591,478,187,816,173,887,222,705,851,032,486,873,136,741,673,856,925,696.00",NaN,NaN,8.71,"781,413.24"
min,1.00,0.00,NaN,NaN,0.00,1.00
25%,"18,317.75","30,000.00",NaN,NaN,4.00,"35,832.00"
50%,"36,634.50","77,500.00",NaN,NaN,8.00,"67,845.00"
75%,"54,951.25","154,000.00",NaN,NaN,15.00,"120,000.00"
max,"73,268.00","900,000,000,000,000,060,934,480,090,350,342,481,100,335,261,807,995,256,832.00",NaN,NaN,50.00,"50,000,000.00"

In [8]:
df.describe(include='all')

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
count,73268.000000,73268,71709,58958,58899,71571,71580,50685,29389,71331,51833,61302,51039,50969,67963,71771,51264,3.842200e+04,44425,70975,67027,60121,51014,49924,40415,53544,46122,44992,36810,54171,46566,70347,64108,65503,70963,71379,68156,0.0,0.0,46223,32072,62128,47688,71071,71365,70961,71572,58229,71408,70946,70853,70315,66565,69474,67244,66447,52670,36283,36769.000000,35804,34973,35133,35097,35014,34991,34977,35371,35344,34515,36198,36022,35679,34906,35819,35715,35749,70444,70508,3.807100e+04
unique,NaN,6,103,3,63,9,737,7192,206,52,52,9984,10,3,125,180,142,NaN,3,25068,23952,4223,4291,1500,1435,8259,8884,4205,5086,951,1245,15063,9188,55,56,16,15,NaN,NaN,1085,825,397,353,6,16,5,3,6,6,8,16,4,32,1055,27,57,2,2,NaN,5,5,5,5,5,5,5,5,5,5,5,5,5,155,2,2,2,3,3,NaN
top,NaN,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",Technical documentation;Blogs;Written Tutorial...,Udemy,10,3,"Developer, full-stack",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,EUR European Euro,NaN,Yearly,HTML/CSS;JavaScript;TypeScript,Python,MySQL,PostgreSQL,AWS,AWS,React.js,React.js,.NET,.NET,npm,Docker,Visual Studio Code,Visual Studio Code,Windows,Windows,Git,Command-line,NaN,NaN,Confluence;Jira Work Management,Jira Work Management,Microsoft Teams,Slack,Indifferent,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,European,None of the above,None of the above,Yes,Independent contributor,NaN,Agree,Agree,Agree,Agree,Agree,Agree,Agree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,15-30 minutes a day,Somewhat long,None of these,Yes,Yes,Yes,Appropriate in length,Easy,NaN
freq,NaN,53507,42962,25341,18118,30276,3669,715,5643,5217,4261,7142,10343,21991,11787,13543,12634,NaN,23267,1250,1021,3563,3994,8719,7350,1959,1703,8181,5025,7436,4298,6753,8815,16645,21653,62055,17602,NaN,NaN,7084,4737,9257,10935,18331,41859,21712,58519,26846,19674,28112,64607,67392,55238,14612,63064,46849,37200,30592,NaN,17527,10711,14779,16891,18674,12916,13080,21689,16368,17666,13652,11871,12961,4658,23767,22716,28027,53883,47886,NaN
mean,36634.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.342434e+52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.242378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.707613e+05
std,21150.794099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.591478e+54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.706850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.814132e+05
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00
25%,18317.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.583200e+04
50%,36634.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.750000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.784500e+04
75%,54951.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.540000e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.200000e+05
max,73268.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000e+56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000e+07

In [21]:
df.DevType.value_counts()

Developer, full-stack                                                                                                                                                                                                                                                                                                                                                                                                                  7142
Developer, back-end                                                                                                                                                                                                                                                                                                                                                                                                                    5301
Developer, front-end                                                                                                                                                                                                                                                                                                                                                                                                                   2385
Developer, front-end;Developer, full-stack;Developer, back-end                                                                                                                                                                                                                                                                                                                                                                         1807
Developer, full-stack;Developer, back-end                                                                                                                                                                                                                                                                                                                                                                                              1535
                                                                                                                                                                                                                                                                                                                                                                                                                                       ...
Developer, front-end;Developer, full-stack;Developer, back-end;Project manager;Product manager;Blockchain                                                                                                                                                                                                                                                                                                                                 1
Developer, front-end;Developer, QA or test;Developer, game or graphics;System administrator                                                                                                                                                                                                                                                                                                                                               1
Database administrator;Academic researcher;Designer;Blockchain                                                                                                                                                                                                                                                                                                                                                                            1
Data scientist or machine learning specialist;Developer, full-stack;Database administrator;Scientist;System administrator                                                                                                                                                                                                                                                                                                                 1
Developer, front-end;Engineer, data;Engineer, site reliability;Developer, full-stack;Developer, back-end;Developer, desktop or enterprise applications;Developer, QA or test;Student;Developer, mobile;Academic researcher;DevOps specialist;Developer, embedded applications or devices;Developer, game or graphics;Cloud infrastructure engineer;Data or business analyst;Designer;Scientist;Product manager;System administrator       1
Name: DevType, Length: 9984, dtype: int64

In [37]:
df.head()

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow for Teams (private knowledge sharing & collaboratio...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write code sometimes as part of my work","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Books / Physical media;Friend or family member;Other online resources (e.g., videos, blogs, foru...",Technical documentation;Blogs;Programming Games;Written Tutorials;Stack Overflow,NaN,14,5,"Data scientist or machine learning specialist;Developer, front-end;Engineer, data;Engineer, site...",20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern Ireland,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., depression, bipolar disorder, etc.);I have an anxiety...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., University, College, etc)",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosting service web GUI;Dedicated version control GUI a...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow for Teams (private knowledge sharing & collaboratio...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc);On t...",Technical documentation;Blogs;Stack Overflow;Online books;Video-based Online Courses;Online chal...,NaN,8,3,"Developer, front-end;Developer, full-stack;Developer, back-end;Developer, desktop or enterprise ...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities like Stack Overflow,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Server;Firebase Realtime Database,Cloud Firestore;Elasticsearch;Firebase Realtime Database;Redis,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow for Teams (private knowledge sharing & collaboratio...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [40]:
pd.options.display.max_colwidth = 100
df.loc[df.DevType.str.contains('data scientist|data or business analyst', case=False ,na=False)].DevType

2        Data scientist or machine learning specialist;Developer, front-end;Engineer, data;Engineer, site...
39       Developer, back-end;Database administrator;DevOps specialist;Cloud infrastructure engineer;Data ...
40       Developer, front-end;Engineer, data;Developer, full-stack;Developer, back-end;Developer, desktop...
41                          Data scientist or machine learning specialist;Engineer, data;Developer, back-end
50                       Data scientist or machine learning specialist;Student;Academic researcher;Scientist
                                                        ...
73229    Data scientist or machine learning specialist;Developer, back-end;Project manager;Data or busine...
73234    Data scientist or machine learning specialist;Developer, front-end;Developer, full-stack;Develop...
73254                 Data scientist or machine learning specialist;Data or business analyst;Product manager
73264                                                          Data scientist or machine learning specialist
73267    Developer, front-end;Engineer, data;Engineer, site reliability;Developer, full-stack;Developer, ...
Name: DevType, Length: 5742, dtype: object

In [78]:
dff = df.loc[df.DevType.str.contains('data scientist|data or business analyst', case=False ,na=False)]
dff.head(1)

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
2,3,"I am not primarily a developer, but I write code sometimes as part of my work","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Books / Physical media;Friend or family member;Other online resources (e.g., videos, blogs, foru...",Technical documentation;Blogs;Programming Games;Written Tutorials;Stack Overflow,NaN,14,5,"Data scientist or machine learning specialist;Developer, front-end;Engineer, data;Engineer, site...",20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern Ireland,GBP\tPound sterling,"32,000.00",Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., depression, bipolar disorder, etc.);I have an anxiety...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,"40,205.00"

In [79]:
dff.describe()

,ResponseId,CompTotal,VCHostingPersonal use,VCHostingProfessional use,WorkExp,ConvertedCompYearly
count,"5,742.00","3,504.00",0.00,0.00,"3,386.00","3,462.00"
mean,"37,209.77","2,853,881,278,828,625,408.00",NaN,NaN,11.96,"175,376.63"
std,"21,186.74","168,934,344,599,866,114,048.00",NaN,NaN,10.11,"672,266.51"
min,3.00,0.00,NaN,NaN,0.00,7.00
25%,"18,657.25","35,000.00",NaN,NaN,4.00,"38,688.00"
50%,"37,755.50","85,000.00",NaN,NaN,9.00,"71,225.50"
75%,"55,936.50","155,250.00",NaN,NaN,17.00,"122,393.00"
max,"73,268.00","10,000,000,000,000,000,000,000.00",NaN,NaN,50.00,"15,000,000.00"

In [80]:
dff['CompFreq_number'] = dff.CompFreq.apply(lambda x : (52/12) if x=='Weekly' else 12 )
dff.loc[dff.CompFreq == 'Monthly', 'CompFreq_number'] = 1

dff[['CompTotal', 'CompFreq', 'CompFreq_number']]

       CompTotal CompFreq  CompFreq_number
2      32,000.00   Yearly            12.00
39           NaN  Monthly             1.00
40    130,000.00   Yearly            12.00
41     19,000.00  Monthly             1.00
50           NaN      NaN            12.00
...          ...      ...              ...
73229 325,000.00   Yearly            12.00
73234        NaN   Weekly             4.33
73254 115,000.00   Yearly            12.00
73264 107,000.00   Yearly            12.00
73267        NaN      NaN            12.00

[5742 rows x 3 columns]

In [81]:
dff['Salary'] = dff.CompTotal / dff.CompFreq_number
dff[['CompTotal', 'CompFreq', 'CompFreq_number', 'Salary',  'WorkExp']]

       CompTotal CompFreq  CompFreq_number    Salary  WorkExp
2      32,000.00   Yearly            12.00  2,666.67      NaN
39           NaN  Monthly             1.00       NaN      NaN
40    130,000.00   Yearly            12.00 10,833.33      NaN
41     19,000.00  Monthly             1.00 19,000.00     3.00
50           NaN      NaN            12.00       NaN     4.00
...          ...      ...              ...       ...      ...
73229 325,000.00   Yearly            12.00 27,083.33    15.00
73234        NaN   Weekly             4.33       NaN    20.00
73254 115,000.00   Yearly            12.00  9,583.33    16.00
73264 107,000.00   Yearly            12.00  8,916.67     6.00
73267        NaN      NaN            12.00       NaN      NaN

[5742 rows x 5 columns]

In [109]:
dff.isna().sum().head(60)

ResponseId                           0
MainBranch                           0
Employment                           0
RemoteWork                         173
CodingActivities                   179
EdLevel                              6
LearnCode                            4
LearnCodeOnline                   1574
LearnCodeCoursesCert              3032
YearsCode                           34
YearsCodePro                       992
DevType                              0
OrgSize                           1066
PurchaseInfluence                 1070
BuyNewTool                         224
Country                              0
Currency                          1059
CompTotal                         2238
CompFreq                          1682
LanguageHaveWorkedWith              36
LanguageWantToWorkWith             365
DatabaseHaveWorkedWith             763
DatabaseWantToWorkWith            1515
PlatformHaveWorkedWith            1463
PlatformWantToWorkWith            2166
WebframeHaveWorkedWith            1925
WebframeWantToWorkWith            2554
MiscTechHaveWorkedWith             952
MiscTechWantToWorkWith            1515
ToolsTechHaveWorkedWith           1838
ToolsTechWantToWorkWith           2413
NEWCollabToolsHaveWorkedWith       109
NEWCollabToolsWantToWorkWith       617
OpSysProfessional use              276
OpSysPersonal use                   83
VersionControlSystem                30
VCInteraction                      399
VCHostingPersonal use             5742
VCHostingProfessional use         5742
OfficeStackAsyncHaveWorkedWith    1970
OfficeStackAsyncWantToWorkWith    3083
OfficeStackSyncHaveWorkedWith      453
OfficeStackSyncWantToWorkWith     1539
Blockchain                          42
NEWSOSites                          18
SOVisitFreq                         69
SOAccount                            7
SOPartFreq                        1029
SOComm                              17
Age                                 49
Gender                              59
Trans                              101
Sexuality                          359
Ethnicity                          178
Accessibility                      322
MentalHealth                       366
TBranch                            878
ICorPM                            2409
WorkExp                           2356
Knowledge_1                       2429
dtype: int64

In [83]:
dff.Salary.value_counts().sort_values(ascending=False)

5,000.00      108
10,000.00      93
8,333.33       81
12,500.00      64
4,166.67       55
             ...
548,333.33      1
8,675.33        1
12,583.33       1
2,290.50        1
27,083.33       1
Name: Salary, Length: 779, dtype: int64

In [110]:
dff.LearnCodeCoursesCert.value_counts()

Udemy                                        306
Coursera;Udemy                               237
Coursera                                     218
Other                                        197
Coursera;Udemy;edX                            91
                                            ...
Codecademy;Udacity;Other                       1
Coursera;Pluralsight;Udacity;Other             1
Coursera;Udemy;Udacity;Skillsoft               1
Coursera;Pluralsight;edX;Other;Skillsoft       1
Coursera;Codecademy;Pluralsight;edX;Other      1
Name: LearnCodeCoursesCert, Length: 142, dtype: int64

In [100]:
dff.loc[dff.CompFreq == 'Monthly'].describe()

,ResponseId,CompTotal,VCHostingPersonal use,VCHostingProfessional use,WorkExp,ConvertedCompYearly,CompFreq_number,Salary
count,"1,668.00","1,204.00",0.00,0.00,"1,102.00","1,191.00","1,668.00","1,204.00"
mean,"36,632.63","839,356,468.05",NaN,NaN,10.46,"143,262.39",1.00,"839,356,468.05"
std,"20,439.71","28,819,877,922.17",NaN,NaN,8.62,"373,510.31",0.00,"28,819,877,922.17"
min,40.00,0.00,NaN,NaN,0.00,24.00,1.00,0.00
25%,"18,989.75","5,000.00",NaN,NaN,4.00,"20,688.00",1.00,"5,000.00"
50%,"36,218.00","20,000.00",NaN,NaN,8.00,"40,956.00",1.00,"20,000.00"
75%,"53,860.25","90,000.00",NaN,NaN,15.00,"72,708.00",1.00,"90,000.00"
max,"73,197.00","1,000,000,000,000.00",NaN,NaN,50.00,"4,704,000.00",1.00,"1,000,000,000,000.00"

In [113]:
dff.DatabaseHaveWorkedWith.value_counts()

Microsoft SQL Server                                352
PostgreSQL                                          278
MySQL                                               204
PostgreSQL;SQLite                                   141
SQLite                                              119
                                                   ...
IBM DB2;MySQL;Oracle                                  1
DynamoDB;Microsoft SQL Server;MongoDB;PostgreSQL      1
DynamoDB;Elasticsearch;MySQL;Oracle                   1
Cassandra;Couchbase;CouchDB;MongoDB;MySQL;SQLite      1
Microsoft SQL Server;Neo4j;Redis                      1
Name: DatabaseHaveWorkedWith, Length: 1153, dtype: int64

In [117]:
dff.loc[dff.DatabaseHaveWorkedWith.str.contains('ibm', na=False, case=False)].DatabaseHaveWorkedWith

749                         Elasticsearch;IBM DB2;Microsoft SQL Server;Redis
1139                                                          IBM DB2;Oracle
3336       IBM DB2;Microsoft SQL Server;MySQL;Oracle;PostgreSQL;Redis;SQLite
3453                                                          IBM DB2;SQLite
3689            IBM DB2;Microsoft SQL Server;MongoDB;MySQL;PostgreSQL;SQLite
                                        ...
72223                                 IBM DB2;MySQL;Oracle;PostgreSQL;SQLite
72604                                                   IBM DB2;MySQL;SQLite
72806                     IBM DB2;MariaDB;Microsoft SQL Server;MongoDB;MySQL
73026    IBM DB2;MariaDB;Microsoft SQL Server;MySQL;Oracle;PostgreSQL;SQLite
73176                  IBM DB2;MariaDB;Microsoft SQL Server;MySQL;PostgreSQL
Name: DatabaseHaveWorkedWith, Length: 217, dtype: object